[[docs]]
  name = "はじめに"
  weight = 10
  identifier = "prologue"
  url = "/docs/prologue/"

[[docs]]
  name = "ご支援について"
  weight = 20
  identifier = "patreon"
  url = "/docs/patreon/"

[[docs]]
  name = "使い方"
  weight = 30
  identifier = "use"
  url = "/docs/use/"

[[docs]]
  name = "ヘルプ"
  weight = 40
  identifier = "help"
  url = "/docs/help/"

[[docs]]
  name = "更新履歴"
  weight = 50
  identifier = "updatelog"
  url = "/docs/updatelog/"

[[docs]]
  name = "その他"
  weight = 60
  identifier = "other"
  url = "/docs/other/"

[[social]]
  name = "Twitter"
  pre = "<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"20\" height=\"20\" viewBox=\"0 0 24 24\" fill=\"none\" stroke=\"currentColor\" stroke-width=\"2\" stroke-linecap=\"round\" stroke-linejoin=\"round\" class=\"feather feather-twitter\"><path d=\"M23 3a10.9 10.9 0 0 1-3.14 1.53 4.48 4.48 0 0 0-7.86 3v1A10.66 10.66 0 0 1 3 4s-4 9 5 13a11.64 11.64 0 0 1-7 2c9 5 20 0 20-11.5a4.5 4.5 0 0 0-.08-.83A7.72 7.72 0 0 0 23 3z\"></path></svg>"
  url = "https://twitter.com/hideki_0403"
  weight = 10

# [[footer]]
#   name = "Privacy"
#   url = "/privacy-policy/"
#   weight = 10
